spring:
  datasource:
    url: jdbc:mysql:///mybatis
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1


mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      wb:
        springboot:
          cache:
            mapper: debug

debug: true

